### ISSUE TITLE
suggest fix related to definition['dimensions'], isimip-qc/isimip_qc/checks/3d.py

### ISSUE THREAD

**Issue by Qing-isotope** [ISI-MIP/isimip-qc#20]
Hi Matthias,

thank you very much for developing the very helpful tool for data quality check! I stumbled upon an error which appears to require a quick fix for variables without "dimension" in their definition.

in https://github.com/ISI-MIP/isimip-qc/blob/6de299daa9492ce1a79399b5cfa7e31be5bfd255/isimip_qc/checks/3d.py#L49-L58

could be revised as something like https://github.com/Qing-isotope/isimip-qc/commit/ee4f3bd4d9cf439cc235d1bf288864ac3f0878d8 :

```
    if 'dimensions' in definition:
        settings_dim_len = len(definition['dimensions'])
        if file_dim_len != settings_dim_len:
            file.critical('Dimension missing (%s found, %s expected). Declare as %s%s. ',
                        file_dim_len, settings_dim_len, file.variable_name, str(definition['dimensions']).replace('\'',''))
    else:
        settings_dim_len = 3
        if file_dim_len != settings_dim_len:
            file.critical('Dimension missing (%s found, %s expected). Declare as %s%s. ',
                        file_dim_len, settings_dim_len, file.variable_name, " unspecified dimension")
```

Hope it works generally as well. 
Best,
Qing

**Comment by thiasB** [comment]
Hi Qing,

thank you very much for reporting your problem. Can you please specify which variable "without dimension" you stumbled upon? I'd like to reproduce what your're seeing.

Best,
Matthias

**Comment by Qing-isotope** [comment]
Hi Matthias,

I was checking output for the peatland sector. Take gpp for example (e.g., model_gswp3-w5e5_obsclim_histsoc_default_gpp_global_monthly_1901_2019.nc), the definition for the variable comes with:
{'comment': 'Grid cell total and PFT information is essential.', 'extension': ['total', '<pft>', '<pt>-total', '<pt>-<pft>'], 'frequency': 'monthly', 'group': 'carbon-fluxes', 'long_name': 'Carbon Mass Flux out of Atmosphere due to Gross Primary Production on Land', 'resolution': '0.5° grid', 'sectors': ['biomes', 'fire', 'forestry', 'peat', 'permafrost'], 'specifier': 'gpp', 'units': 'kg m-2 s-1', 'valid_max': 1e-06, 'valid_min': 0.0}
without information for 'dimensions', therefore str(definition['dimensions']) doesn't exist when I run check().

cheers,
Qing

**Comment by thiasB** [comment]
Alright, thanks. Fix https://github.com/ISI-MIP/isimip-qc/commit/2e14a7f60ec2b8394df983b86c7f6ea45cdf22ba will be included in the next release.

[1] https://github.com/ISI-MIP/isimip-qc/releases/tag/3.3.2
[2] https://pypi.org/project/isimip-qc/3.3.2/

**Comment by thiasB** [comment]
fixed and released
